src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name="home"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('features/', views.FeaturesView.as_view(), name="features"),
    path('examples/', views.ExamplesView.as_view(), name="examples"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('ftmap/', include(('ftmap.urls', 'ftmap'), namespace='ftmap')),
    path('signup/', include(('user_app.urls', 'user_app'), namespace='user_app')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
               static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/ftmap/urls.py
from django.urls import path

from . import views
app_name = 'ftmap'
urlpatterns = [
    path('', views.UserHomeView.as_view(), name="user_home"),
    path("create/", views.JobCreate.as_view(), name="job_create"),
    path("<slug>/", views.JobDetail.as_view(), name="job_detail"),
]

src/user_app/urls.py
from django.conf.urls import url
from . import views
app_name = 'user_app'
urlpatterns = [
    url('', views.signup, name='signup'),
]

src/templates/about.html
{% extends "base.html" %}

{% load static from staticfiles %}


{% block title %}About{% endblock %}

{% block content %}
  <img style="width:100%;" id="image" src="{% static '/images/ftmap_example.png' %}">

  <div style="margin:70px">
    <p>Thanks for your interest in FTMap. Please contact us if you have any questions not listed on this page.</p>
    <h2>Usage</h2>
    <p></p>
    <h2>Trouble Shooting</h2>
    <p></p>
    <h2>Frequently Asked Questions</h2>
    <ul>
      <li><a href="#account">Do I have to create an account to use FTPlus?</a></li>
      <li><a href="#username">What if I forgot my password or username?</a></li>
      <li><a href="#change-user-data">What if I no longer have access to the email address used to create my account?</a></li>
      <li><a href="#confidentiality">Will my uploaded structures be kept confidential?</a></li>
      <li><a href="#delete">How do I delete my account?</a></li>
      <li><a href="#result-content">What is the difference between a probe, probe cluster, consensus site, crosscluster
        and hotspot?</a></li>
      <li><a href="#probes">What probes are used for mapping?</a></li>
      <li><a href="#cluster-names">What are the numbers after "crosscluster"?</a></li>
      <li><a href="#source-code">Can I have a copy of the source code?</a></li>
      <li><a href="#cite">How do I cite FTPlus?</a></li>
    </ul>

    <a name="account"><h3>Do I have to create an account to use FTPlus?</h3></a>
    <p>An account is required for the use of FTPlus. This ensures that you can make the most out of FTPlus by keeping
    all of your jobs secure and easy to access.</p>
    <a name="username"><h3>What if I forgot my password or email?</h3></a>
    <p>To reset your password, simply go to the login page and select "Forgot Password". If you have forgotten the
      email address you used to create an account please contact us and include your first and last name. Once you have
      the email address associated with your account, you can reset your password.
    </p>
    <a name="change-user-data"><h3>What if I no longer have access to the email address used to create my account??</h3></a>
    <p>Please use the contact form so that we can update your account.</p>
    <a name="confidentiality"><h3>Will my uploaded structures be kept confidential?</h3></a>
    <p>While we do our best to maintain best practices, we cannot guarantee confidentiality. However, jobs are never
      shared with other users and are permanently deleted after 30 days. If confidentiality is required, a commercial
      version can be obtained through <a href="https://acpharis.com/" target="_blank">Acpharis</a>.</p>
    <a name="delete"><h3>How do I delete my account?</h3></a>
    <p>To delete your account, please go to your homepage and select "My Account". There is an option to delete your
    account.</p>
    <a name="result-content"><h3>What is the difference between a probe, probe cluster, consensus site, crosscluster
      and hotspot?</h3></a>
    <p></p>
    <a name="probes"><h3>What probes are used for mapping?</h3></a>
    <p>There are 16 probes that are used for mapping.</p>
    <a name="cluster-names"><h3>What are the numbers after "crosscluster"?</h3></a>
    <p>The numbers after crosscluster represent the rank of the hotspot (idexed at 0) followed by the number of
      probe clusters in the hotspot. For example crosscluster.000.024 is the highest ranked hotspot and it is comprised
      of 24 probe clusters.</p>
    <a name="source-code"><h3>Can I have a copy of the source code?</h3></a>
    <p>Unfortunately, we are unable to provide the source code for FTPlus. Please contact
      <a href="https://acpharis.com/" target="_blank">Acpharis</a> if you would like to run FTPlus on your own servers.</p>
    <a name="cite"><h3>How do I cite FTPlus?</h3></a>
    <p>Please cite the following references:<br></p>
  </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>

{% load static from staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="manifest" href="/media/icons/site.webmanifest">
  <link rel="mask-icon" href="/media/icons/safari-pinned-tab.svg" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-config" content="/media/icons/browserconfig.xml">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/sandstone/bootstrap.min.css">
  <title>FTPlus | {% block title %}{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top" id="navbar">
    <a class="navbar-brand" href="{% url 'home' %}">FTPlus</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'ftmap:user_home' %}">My FTPlus<span class="sr-only">(current)</span></a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'features' %}">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'examples' %}">Examples</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
      </ul>
      <style type="text/css">.sidebar-nav li{list-style-type: none;}</style>
      <ul class="sidebar-nav" >
       {% if user.is_authenticated %}
        <li class="text-muted">User: {{ user.get_username }}</li>
         <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
       {% else %}
         <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
         <li><a href="{% url 'user_app:signup'%}">Signup</a></li>
       {% endif %}
       </ul>
    </div>
  </nav>
  {% if config.BANNER_ON == 'yes' %}
    {% if config.ACCEPTING_JOBS == 'yes' %}
    <div class="alert alert-dismissible alert-info">
    <strong>{{ config.BANNER_MESSAGE }}</strong>
    </div>
    {% elif config.ACCEPTING_JOBS == 'no' %}
      <div class="alert alert-dismissible alert-danger">
      <strong>{{ config.BANNER_MESSAGE }}</strong>
      </div>
    {% endif %}
  {% else %}
    {% if config.ACCEPTING_JOBS == 'no' %}
      <div class="alert alert-dismissible alert-danger">
      <strong>{{ config.BANNER_MESSAGE }}</strong>
      </div>
    {% endif %}
  {% endif %}
  {% block content %}{% endblock %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.8/raphael.min.js"></script>
  <script src="https://unpkg.com/ngl"></script>
{% block extra_js %}{% endblock %}
</body>

<footer>
  <div class="footer bg-light py-5" id="footer">
    <p class="text-muted text-center my-0">Developed by the <a href="https://vajdalab.org/" target="_blank">Vajda Lab</a>
      at <a href="https://www.bu.edu/" target="_blank">Boston University</a>.
      <br>Copyright &copy; 2020. All rights reserved. Non-commercial use only.</p>
  </div>
</footer>

</html>

src/templates/contact.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block title %}Contact Us{% endblock %}

{% block content %}
  <img style="width:100%;" src="{% static '/images/ftmap_example.png' %}">
  <div style="margin:70px">
    <h1>Contact Us</h1>
    <p>Please use the contact form on the <a href="https://www.vajdalab.org/contact" target="_blank">Vajda Lab website</a>
      and select "FTMap" as the category.<br>
      If contacting us about a particular job, please include the job number in your message.</p>
  </div>

{% endblock %}

src/templates/examples.html
{% extends "base.html" %}

{% load static from staticfiles %}


{% block title %}Examples{% endblock %}

{% block content %}
<style>
  .row {display: flex;}
  .column { flex: 50%;}
  .table { width: max-content}
</style>
<div class="row" style="margin:70px">
  <div class="column";>
    <div style="margin-right: 3px">
  <h1>FTPlus Examples</h1>

  <table class="table table-hover">
  <thead>
    <tr>
      <th>Structure</th>
      <th>PDB</th>
      <th>Download</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for example in example_list %}
      <tr>
        <td>{{example.title}}</td>
        <td>{{example.pdb_id}}</td>
        <td><a download="{{example.pdb_file}}" href="{{ MEDIA_URL }}{{example.pdb_file}}">PDB
        </a><a download="{{example.pse_file}}" href="{{ MEDIA_URL }}{{example.pse_file}}">PSE</a>
        </td>
        <td><label for="viewport" class="container">{{ item.title }}
          <input type="radio" checked="checked" name="radio" value="{{ MEDIA_URL }}{{ example.pdb_file }}">
          <span class="checkmark"></span></label>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
</div>
  <div class="column">
    <meta name="viewport" content="width=device-width">
    <div id="viewport" style="width:100%; height:400px;"></div>
    <p>Mouse-over to identify atoms and bonds. Use left click to rotate, right click to zoom and press
      scroll wheel to move object. Use two fingers to zoom with a trackpad.</p>
      <p>Molecular viewer powered by <a href="http://nglviewer.org/" target="_blank">NGL.</a></p>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/ngl_viewer.js' %}"></script>
<script type="text/javascript">

// Create NGL Stage object
var stage = new NGL.Stage( "viewport", {backgroundColor: "white"});


// Handle window resizing
window.addEventListener( "resize", function( event ){
    stage.handleResize();
}, false );

function addElement (el) {
  Object.assign(el.style, {
    position: "absolute",
    zIndex: 10
  });
  stage.viewer.container.appendChild(el)
}

function createElement (name, properties, style) {
  let el = document.createElement(name);
  Object.assign(el, properties);
  Object.assign(el.style, style);
  return el
}

$(document).on("click","input[name='radio']", function(){
    let new_file = $("input[name='radio']:checked").val();
    stage.removeAllComponents();
    update_ngl(new_file);
});

// Load 1st example
  let first_file = "{{ MEDIA_URL }}{{ example_list.first.pdb_file }}";
  update_ngl(first_file)

</script>

{% endblock %}

src/templates/features.html
{% extends "base.html" %}

{% load static from staticfiles %}


{% block title %}Features{% endblock %}

{% block content %}
<div style="margin:70px">
  <h1>Features</h1>
  <h2>Current</h2>
  <h3>FTMap</h3>
  <h2>Coming Soon</h2>
  <h3>FTSite</h3>
</div>
{% endblock %}

src/templates/home.html
{% extends "base.html" %}

{% load static from staticfiles %}


{% block title %}Home{% endblock %}

{% block content %}
  <img style="width:100%;" src="{% static '/images/ftmap_example.png' %}">
  <div style="margin:70px">
    <h1>Welcome to FTPlus</h1>
    <p>FTPlus is a single server designed to combine the best features of FTMap, FTSite and FTDyn into a simple,
      user-friendly website. The algorithms are the same but the user experience is even better. We thank you for your
      patience as we release these features.
    </p>
  </div>
{% endblock %}