src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name="home"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('features/', views.FeaturesView.as_view(), name="features"),
    path('examples/', views.ExamplesView.as_view(), name="examples"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('ftmap/', include(('ftmap.urls', 'ftmap'), namespace='ftmap')),
    path('signup/', include(('user_app.urls', 'user_app'), namespace='user_app')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
               static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/ftmap/urls.py
from django.urls import path

from . import views
app_name = 'ftmap'
urlpatterns = [
    path('', views.UserHomeView.as_view(), name="user_home"),
    path("create/", views.JobCreate.as_view(), name="job_create"),
    path("<slug>/", views.JobDetail.as_view(), name="job_detail"),
]

src/templates/ftplus/job_create.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %}New Job{% endblock %}


{% block content %}
<div style="margin:70px">
  {% if config.ACCEPTING_JOBS == 'yes' %}
    <form action="." method="POST" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}

    {{ form.non_field_errors }}

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field.errors }}
      {{ hidden_field }}
    {% endfor %}

    <table>
      {% for field in form.visible_fields %}
        <tr>
          <th>{{ field.label_tag }}</th>
          <td>
            {{ field.errors }}
            {{ field }}
            {{ field.help_text }}
          </td>
        </tr>
      {% endfor %}
    </table>
    <input type="submit" class="btn btn-primary pull-right" value="Start job {% if not form.instance.pk %}&amp; preview {% endif %}">
    </form>
  {% else %}
    <p>We are not currently accepting new jobs. Please try again later.</p>
  {% endif %}
</div>


{% endblock %}

src/templates/ftplus/job_detail.html
{% extends "base.html" %}

{% if user.is_authenticated %}

{% load static from staticfiles %}


{% block title %}{{ job.title }}{% endblock %}

{% block content %}
  <div style="margin:70px">
    <div>
      <h2>{{job.title}}</h2>
    </div>
    <div class="column">
    <meta name="viewport" content="width=device-width">
    <div id="viewport" style="width:100%; height:400px;"></div>
    <p>Mouse-over to identify atoms and bonds. Use left click to rotate, right click to zoom and press
      scroll wheel to move object. Use two fingers to zoom with a trackpad.</p>
      <p>Molecular viewer powered by <a href="http://nglviewer.org/" target="_blank">NGL.</a></p>
  </div>
  </div>
{% endblock %}

{% endif %}


{% block extra_js %}
<script src="{% static 'js/ngl_viewer.js' %}"></script>
<script type="text/javascript">

// Create NGL Stage object
var stage = new NGL.Stage( "viewport", {backgroundColor: "white"});


// Handle window resizing
window.addEventListener( "resize", function( event ){
    stage.handleResize();
}, false );

function addElement (el) {
  Object.assign(el.style, {
    position: "absolute",
    zIndex: 10
  });
  stage.viewer.container.appendChild(el)
}

function createElement (name, properties, style) {
  let el = document.createElement(name);
  Object.assign(el, properties);
  Object.assign(el.style, style);
  return el
}

// $(document).on("click","input[name='radio']", function(){
//     let new_file = $("input[name='radio']:checked").val();
//     stage.removeAllComponents();
//     update_ngl(new_file);
// });

// Load 1st example
  let first_file = "{{ MEDIA_URL }}{{ job.in_file }}";
  update_ngl(first_file)

</script>

{% endblock %}

src/templates/ftplus/user_home.html
{% extends "base.html" %}

{% if user.is_authenticated %}

{% load static from staticfiles %}


{% block title %}Home{% endblock %}

{% block content %}
  <div style="margin:70px">
    <h1>Welcome to your FTPlus Account Page</h1>
    <h3>Use this page to view and edit previous jobs or to create new jobs.</h3>
    <h5>You are allowed to submit {{ user.max_job_submission }} jobs a day.</h5>
  {% if config.ACCEPTING_JOBS == 'yes' %}
    {% if user.daily_job_count < user.max_job_submission %}
      <p>You have submitted {{ user.daily_job_count }} jobs today.</p>
      <button type="button" onclick="location.href='{% url 'ftmap:job_create' %}'" type="button" class="btn btn-primary btn-lg">Start a new job</button>
    {% elif user.daily_job_count >= user.max_job_submission %}
      You have reached your submission limit for today.
    {% endif %}
  {% endif %}
  </div>
  <div style="margin:70px">
    <h2>Jobs in progress:</h2>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <table id="in-progress" class="table table-striped table-bordered" style="width:100%">
            <thead>
              <tr>
                <th>Created</th>
                <th>Job</th>
                <th>PDB ID</th>
                <th>Status</th>
                <th>User</th>
              </tr>
            </thead>
            <tbody>
            {% for job in job_list %}
              {% if job.status == job.STATUS_ACTIVE %}
                <tr>
                  <td>{{ job.created }}</td>
                  <td><a href="{%url 'ftmap:job_detail' slug=job.uuid %}">{{job.title}}</a></td>
                  <td>{{ job.pdb_id }}</td>
                  <td>{{ job.get_status_display }}</td>
                  <td>{{ job.user }}</td>
                </tr>
              {% endif %}
            {% endfor %}
          </tbody>
          </table>
        </div>
      </div>
    </div>
    </div>
  <div style="margin:70px">
    <h2>Completed jobs:</h2>
        <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <table id="completed" class="table table-striped table-bordered" style="width:100%">
            <thead>
              <tr>
                <th>Created</th>
                <th>Job</th>
                <th>PDB ID</th>
                <th>Status</th>
                <th>User</th>
              </tr>
            </thead>
            <tbody>
            {% for job in job_list %}
              {% if job.status != job.STATUS_ACTIVE %}
                <tr>
                  <td>{{ job.created }}</td>
                  <td>{{ job.title }}</td>
                  <td>{{ job.pdb_id }}</td>
                  <td>{{ job.get_status_display }}</td>
                  <td>{{ job.user }}</td>
                </tr>
              {% endif %}
            {% endfor %}
          </tbody>
          </table>
        </div>
      </div>
    </div>
    </div>
  </div>
{% endblock %}

{% endif %}